import {
  RESOURCE_SECTIONS,
  EMPTY_SECTION_MESSAGE,
  DOC_PENDING_LABEL,
  DEFAULT_DOC_ICON,
} from './data';

export {
  RESOURCE_SECTIONS,
  EMPTY_SECTION_MESSAGE,
  DOC_PENDING_LABEL,
  DEFAULT_DOC_ICON,
};
