export {
  FOCUS_SECTIONS,
  WELCOME_HERO_IMAGE,
  LANDING_HERO_CAROUSEL,
  EDUCATION_SECTION_ID,
  STATS_SECTION_ID,
  FLAGSHIP_SECTION_ID,
  SIX_PILLARS_PATH,
  IMPACT_SECTION_COPY,
  IMPACT_HERO_STATS,
  IMPACT_GROUPS,
} from './data';

export {
  WELCOME_HERO_LAYOUT,
  calculateWelcomeHeroLayout,
} from './welcomeHeroLayout';
